use_frameworks!

target 'WJGlobalTimer_Example' do
  pod 'WJGlobalTimer', :path => '../'

  target 'WJGlobalTimer_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
